---

- include_vars: "../vars/main.yml"

- name: Install packages for Debian based distros.
  apt: name={{item}} update_cache=yes
  with_items:
        - g++
        - make
  become: yes
  become_user: root

- name: download_nmap_source
  get_url: url={{ nmap_download_url }} dest=/tmp/nmap-{{ nmap_version }}.tar.bz2

- name: Save tmp path for nmap
  stat: path=/tmp/nmap-{{ nmap_version }}
  register: nmap_tmp_dir

- name: Uncompress Nmap
  unarchive: src=/tmp/nmap-{{ nmap_version }}.tar.bz2 dest=/tmp copy=no
  when: nmap_tmp_dir.stat.exists == False

- name: Save location of nmap binary
  stat: path=/usr/local/bin/nmap
  register: bin

- name: Execute configure script
  shell: './configure chdir=/tmp/nmap-{{ nmap_version }}'
  when: bin.stat.exists == False
  become: yes
  become_user: root

- name: Run make
  shell: 'make chdir=/tmp/nmap-{{ nmap_version }}'
  when: bin.stat.exists == False
  become: yes
  become_user: root

- name: Install Nmap binary
  shell: 'make install chdir=/tmp/nmap-{{ nmap_version }}'
  become: yes
  become_user: root
  when: bin.stat.exists == False