---
# Synchronize two directories on one remote host (the inverse of push).

- name: check if remote file exists 
  stat: path={{ remote_absolute_path }}
  become: yes
  register: remote_file_exists

- name: check if local host exists
  local_action: stat path={{ host_absolute_path }}
  become: no
  register: host_file_exists

- name: pull files from remote server to host
  synchronize:
    mode: pull
    src: "{{ remote_absolute_path }}"
    dest: "{{ host_absolute_path }}"
    recursive: true
    verify_host: false
  when:
    - remote_file_exists.stat.exists
    - host_file_exists.stat.exists
  
    